# Personal

* [1fichier.com - Anonymous file sharing](https://1fichier.com/)
* [6.3 million+ Stunning Free Images to Use Anywhere - Pixabay](https://pixabay.com/)
* [A Soft Murmur](https://asoftmurmur.com/)
* [Acer Movies](https://acermovies.fun/)
* [Androeed.Store - Android games, Android Mods, Hacks](https://androeed.store/)
* [anidash.pages.dev](https://anidash.pages.dev/)
* [Animeya - Watch Anime, Stream Subbed and Dubbed Anime in HD](https://animeya.cc/home)
* [ApkVision - MOD APK Games and App for Android (apkvision.org)](https://apkvision.org/)
* [AppOnFly Cloud - Windows VPS, SQL, Hosted desktop](https://www.apponfly.com/)
* [ARC Prize - Leaderboard](https://arcprize.org/leaderboard)
* [AutoDraw](https://autodraw.com/)
* [Awesome Open Source](https://awesomeopensource.com/)
* [Beautiful Free Images & Pictures | Unsplash](https://unsplash.com/)
* [Best Obsidian Plugins](https://www.obsidianstats.com/)
* [Bitsearch | New Generation Torrent Search Engine](https://bitsearch.to/)
* [BlackHatWorld](https://www.blackhatworld.com/)
* [Booktracker](https://booktracker.org/)
* [Botostore - Best online chat bots and assistants](https://botostore.com/)
* [BUNKR - Privacy-focused File Hosting](https://bunkr.ph/)
* [Buzzheavier - Anonymous file sharing](https://buzzheavier.com/)
* [Cambridge Dictionary](https://dictionary.cambridge.org/)
* [check down website](https://www.isitdownrightnow.com/)
* [Claude](https://claude.ai/)
* [Clipdrop](https://clipdrop.co/)
* [Cliq (cliq.zoho.in)](https://cliq.zoho.in/)
* [cobalt.directory](https://cobalt.directory/)
* [Code Beautify and Code Formatter](https://codebeautify.org/)
* [Coding Cat | Nyan Cat's cousin who is listening to lo-fi](https://hostrider.com/)
* [Collins English Dictionary](https://www.collinsdictionary.com/dictionary/english)
* [Compiler Explorer](https://godbolt.org/)
* [cowyo — A shared scratchpad with no setup](https://cowyo.com/)
* [CurseForge](https://www.curseforge.com/)
* [delphitools — privacy-first browser tools](https://delphi.tools/)
* [DeviantArt - The Largest Online Art Gallery and Community](https://www.deviantart.com/)
* [Dictionary, translation | French, Spanish, German | Reverso](https://dictionary.reverso.net/)
* [DISBOARD | Public Discord Server List](https://disboard.org/)
* [DODI Repacks](https://dodi-repacks.site/)
* [DownGit](https://downgit.github.io/)
* [Download android Mod app & games Apk | DlAndroid](https://dlandroid.com/)
* [Download Latest Top Torrents by Subcategories torrentGalaxy](https://torrentgalaxy.one/)
* [Download music, movies, games, software! The Pirate Bay](https://thepiratebay.org/index.html)
* [Downloadha](https://www.downloadha.com/)
* [Downloadly](https://downloadly.ir/)
* [Downloadly – Free Software Download](https://downloadlynet.ir/)
* [Dribbble - Discover the World’s Top Designers](https://dribbble.com/)
* [EasyEngineering Networks](https://easyengineering.net/)
* [eBookBB - Find Yourself Something New to Read](https://ebookbb.in/)
* [Edu Mail Generator - TempuMail](https://tempumail.com/)
* [Educational Hub - Learn & Grow](https://educationalhub.in/)
* [Electronic Library. Download books for free.](https://en.booksee.org/)
* [Electronic library. Download books for free. Book Search](https://libcats.org/)
* [Email Generator - temp mail, fake email](https://generator.email/)
* [Emkei's Anonymous Mailer](https://emkei.cz/)
* [Everythingmoe](https://everythingmoe.pages.dev/)
* [Expired Domains](https://www.expireddomains.net/)
* [ExtraTorrent.st The World's Largest BitTorrent System](https://extratorrent.st/)
* [FACTLY - Making Public Data Meaningful](https://factly.in/)
* [favicon.io - The best Favicon Generator](https://favicon.io/)
* [FMHY Tracker](https://fmhy-tracker.pages.dev/)
* [Free Chess.com Insights](https://chessinsights.xyz/)
* [Free Cloud Hosting by OnWorks](https://www.onworks.net/)
* [Free Vector Icons and Stickers - Flaticon](https://www.flaticon.com/)
* [FreeCourseSite](https://fcsnew.net/)
* [Freepik | Graphic Resources for everyone](https://www.freepik.com/)
* [Frontpage -- Terms of Service; Didn't Read (tosdr.org)](https://tosdr.org/)
* [GeeksforGeeks](https://www.geeksforgeeks.org/)
* [GIPHY | Search All the GIFs & Make Your Own Animated GIF](https://giphy.com/)
* [Git.ir](https://git.ir/)
* [Gmail (mail.google.com)](https://mail.google.com/mail/u/0/)
* [Google Drive Links - For Udemy Courses,Ebooks,Tutorials,Programming,Games,Novels,Songs](https://googledrivelinks.com/)
* [Google Trends](https://trends.google.com/trends/)
* [HackerRank](https://www.hackerrank.com/dashboard)
* [HacksNation - A Place Where Everyone Can Learn](https://hacksnation.com/)
* [Home - Replit (replit.com)](https://replit.com/~)
* [Home Page - Watch the Latest Movies and TV Shows for Free on Flixtor.to](https://flixtor.to/home)
* [Home | ZeroFS](https://zerofs.link/)
* [Hot Audiobooks (Online)](https://hotaudiobooks.com/)
* [Icon Archive - Search 735,802 free icons](https://iconarchive.com/)
* [ImDb filter](https://www.imdb.com/search/title/?title_type=feature,tv_movie,short,tv_miniseries,tv_series&release_date=1990-01-01,&user_rating=7.5,10&num_votes=10000,&adult=include&sort=num_votes,desc)
* [imdb popular](https://www.imdb.com/search/title/?title_type=feature,tv_series,tv_movie,tv_miniseries&user_rating=7,10&num_votes=5000,&adult=include&count=100)
* [Instagram](https://www.instagram.com/)
* [Instance Directory - Welcome!](https://privatebin.info/directory/)
* [InterviewBit: Coding Interview Questions](https://www.interviewbit.com/)
* [Investopedia - Sharper Insight. Smarter Investing.](https://www.investopedia.com/)
* [Invidious](https://yewtu.be/feed/popular)
* [IT Tools - Handy online tools for developers](https://it-tools.tech/)
* [JustWatch - The Streaming Guide](https://www.justwatch.com/)
* [Kimi AI with K2.6 | Better Coding, Smarter Agents](https://www.kimi.com/)
* [Last Name Meanings and Origins | Ancestry.com®](https://www.ancestry.com/last-name-meaning)
* [Learn X in Y Minutes: Scenic Programming Language Tours](https://learnxinyminutes.com/)
* [learnbyexample - I know Python basics, what next?](https://learnbyexample.github.io/python-intermediate/)
* [LimeTorrents - Download Verified Torrents](https://www.limetorrents.fun/)
* [Live trending GitHub repositories — daily momentum ranking | Trendshift](https://trendshift.io/)
* [LiveBench](https://livebench.ai/#/)
* [Lumen](https://lumendatabase.org/)
* [lwalpapers - A collection of 900+ unique desktop wallpapers!](https://wallpaper.castorisdead.xyz/)
* [Mathematics Stack Exchange](https://math.stackexchange.com/)
* [MDN Web Docs](https://developer.mozilla.org/)
* [MediaSavvy | Piracy Wiki](https://mediasavvy.pages.dev/)
* [Medium](https://medium.com/)
* [Meta AI](https://meta.ai/)
* [Mgread.io](https://mgread.io/)
* [MineBench](https://minebench.ai/)
* [epaperWave](https://epaperwave.com/)
* [Mnemonic Dictionary](https://mnemonicdictionary.com/)
* [MODYOLO - Free MOD APK Game & Premium APP for Android](https://modyolo.com/)
* [MuscleWiki - Simplify your workout](https://musclewiki.com/)
* [Myinstants | The largest instant sound buttons website in India!](https://www.myinstants.com)
* [Neetcode](https://neetcode.io/practice)
* [O2TvSeries - Download TV Series and TV Shows for Free](https://o2tvseries4u.com/)
* [Oldtoons - Your childhood toons](https://oldtoons.world/)
* [OneHack a.k.a 1Hack - Together WE Learn 🚀](https://onehack.st/)
* [Online Courses - Learn Anything, On Your Schedule | Udemy](https://www.udemy.com/)
* [Online Etymology Dictionary](https://www.etymonline.com/)
* [Online video editor by Microsoft Clipchamp](https://clipchamp.com/en/)
* [P30DAY](https://www.p30day.ir/)
* [Paul Falstad's Applets](https://www.falstad.com/)
* [pdfdrive.com](https://www.pdfdrive.com/)
* [Pew Research Center](https://www.pewresearch.org/)
* [Pixelcut | Free AI Photo Editor](https://www.pixelcut.ai/)
* [Polymarket | The World's Largest Prediction Market](https://polymarket.com/)
* [Practice typing by retyping ENTIRE novels — TypeLit.io](https://www.typelit.io/)
* [PrimeFlix](https://helposter.com/)
* [Privacy Tools: Fight Mass Surveillance with Encryption](https://www.privacytools.io/)
* [Product Hunt – The best new products in tech.](https://www.producthunt.com/)
* [Project Euler](https://projecteuler.net/)
* [Proton Mail](https://mail.proton.me/u/0/inbox)
* [ProxyGalaxy](https://proxygalaxy.cc/)
* [Puzzling Stack Exchange](https://puzzling.stackexchange.com/)
* [Qwen](https://chat.qwenlm.ai/)
* [REDFLIX](https://redflix.co/)
* [Remove objects from photos | Magic Eraser by Magic Studio](https://magicstudio.com/magiceraser/)
* [rutor.info :: Свободный торрент трекер](https://rutor.info/)
* [Sci-Hub](https://sci-hub.usualwant.com/)
* [Search LeetCode Users](https://search.nextleet.com/)
* [Secure email: Tutanota free encrypted email.](https://tutanota.com/)
* [seedpool - (seedpool.org)](https://seedpool.org/)
* [Sejda helps with your PDF tasks](https://www.sejda.com/)
* [ShareBin.eu - Free File Sharing and Live Notepad](https://sharebin.eu/)
* [SharePad.io | Free code interview tool](https://sharepad.io/)
* [Short.io — URL shortener with custom branded domains](https://short.io/)
* [SigStick Sticker Maker](https://www.sigstick.com/)
* [Similarsites.com - Easily Explore alternative websites](https://www.similarsites.com/)
* [SimilarWeb](https://www.similarweb.com/)
* [Skidrow & Reloaded Games](https://www.skidrowreloaded.com/)
* [SoftArchive – Unlimited Download Source](https://sanet.st/)
* [SplitMySong.com: Audio Separation powered by AI](https://www.splitmysong.com/)
* [Steam Charts - Tracking What's Played](https://steamcharts.com/)
* [Steam Workshop Downloader :: IO](https://steamworkshopdownloader.io/)
* [STEAMUNLOCKED » Free Steam Games Pre-installed for PC (steamunlocked.org)](https://steamunlocked.org/)
* [Stock Screener and fundamental analysis tool for Indian stocks - Screener](https://www.screener.in/)
* [StudyStream | Study With Strangers | Study Together](https://app.studystream.live/focus/room)
* [Super Pass Live Preparation with India's Super Teachers](https://testbook.com/online-test-series)
* [T4TSA | Watch, Relax, Repeat](https://t4tsa.cc/)
* [Telegram Stickers Directory — Discover best stickers and animations](https://tlgrm.eu/stickers)
* [Telegram Web](https://web.telegram.org/k/)
* [Temp Mail - Free Edu / .COM Temporary Mails](https://etempmail.com/)
* [Temporary phone number | Receive SMS online (receivesms.cc)](https://receivesms.cc/)
* [Temporary phone number | Receive SMS online (smss.net)](https://smss.net/)
* [Terabox Downloader](https://teradownloader.com/)
* [Test Ad Block - Toolz](https://d3ward.github.io/toolz/adblock)
* [The On-Line Encyclopedia of Integer Sequences® (OEIS®)](http://oeis.org/)
* [The True Size Of ...](https://thetruesize.com/)
* [Torrent Search Engine | 1337x.to](https://x1337x.ws/)
* [TradingView — Track All Markets](https://in.tradingview.com/)
* [Transfer Playlists Between Music Services | Tune My Music](https://www.tunemymusic.com/home)
* [TrueUp | The CareerOS for people in tech](https://www.trueup.io/)
* [Try It Online - code runner](https://tio.run/#)
* [Tutanota](https://mail.tutanota.com/mail/)
* [TV Shows | Movy](https://www.movy.sx/browse/tv)
* [Unabridged Audiobooks Free Download](http://audiobookbay.fi/)
* [Unblocked - Access your favourite blocked sites](https://unblock-it.com/)
* [Unblockit - Proxies to access your favourite blocked sites](https://unblockit.pages.dev/)
* [UniqueStream - Your #1 Streaming Source](https://uniquestream.net/)
* [vadapav.mov - Download Movies / Tv Shows Free!](https://vadapav.mov/)
* [Verywell Mind - Know More. Live Brighter.](https://www.verywellmind.com/)
* [Vibemathed](https://vibemathed.com/)
* [Vocal Remover and Isolation (AI)](https://vocalremover.org/)
* [Wait But Why](https://waitbutwhy.com/)
* [Watch Anime Online - Streaming Subbed HD | Animegg.org](https://www.animegg.org/)
* [Watch Latest Movies & Shows Episode Online Free](https://www.lookmovie2.to/)
* [web.dev](https://web.dev/)
* [WebMD - Better information. Better health.](https://www.webmd.com/)
* [freemediaheckyeah (fmhy.bid)](https://fmhy.bid/)
* [Whois Lookup, Domain Availability & IP Search - DomainTools](https://whois.domaintools.com/)
* [winget.run | Finding winget packages made simple.](https://winget.run/)
* [Worldwide Overview | Cloudflare Radar](https://radar.cloudflare.com/)
* [XDA Forums](https://forum.xda-developers.com/)
* [Xiaomi MiMo Studio](https://aistudio.xiaomimimo.com/#/c)
* [xkx - Jaz Mail](https://xkx.me/)
* [Yasdl](https://www.yasdl.com/)
* [YOPmail - Disposable Email Address](https://yopmail.com/)
* [YouTube to MP4 converter (No ads) - AMP4](https://amp4.cc/)
* [✉ Guerrilla Mail - Disposable Temporary E-Mail Address](https://www.guerrillamail.com/)
